# a mybinder.org-ready environment for demoing jupyterlab_blockly_ipylgbst
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyterlab-blockly-ipylgbst-demo
#
name: jupyterlab-blockly-ipylgbst-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.11.0a0
  - jupyterlab >=4,<5.0.0a0
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  # packages needed for build to succeed
  - certipy
  - async_generator
  # additional packages for demos
  # - ipywidgets
